/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_backend_sdl_Sdl */

#ifndef _Included_com_badlogic_gdx_backend_sdl_Sdl
#define _Included_com_badlogic_gdx_backend_sdl_Sdl
#ifdef __cplusplus
extern "C" {
#endif
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_TIMER
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_TIMER 1L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_AUDIO
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_AUDIO 16L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_VIDEO
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_VIDEO 32L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_CDROM
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_CDROM 256L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_JOYSTICK
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_JOYSTICK 512L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_NOPARACHUTE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_NOPARACHUTE 1048576L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_EVENTTHREAD
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_EVENTTHREAD 16777216L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_EVERYTHING
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_INIT_EVERYTHING 65535L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_SWSURFACE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_SWSURFACE 0L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_HWSURFACE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_HWSURFACE 1L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_ASYNCBLIT
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_ASYNCBLIT 4L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_ANYFORMAT
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_ANYFORMAT 268435456L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_HWPALETTE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_HWPALETTE 536870912L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_DOUBLEBUF
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_DOUBLEBUF 1073741824L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_FULLSCREEN
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_FULLSCREEN -2147483648L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_OPENGL
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_OPENGL 2L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_OPENGLBLIT
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_OPENGLBLIT 10L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_RESIZABLE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_RESIZABLE 16L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_NOFRAME
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_NOFRAME 32L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_RED_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_RED_SIZE 0L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_GREEN_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_GREEN_SIZE 1L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_BLUE_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_BLUE_SIZE 2L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ALPHA_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ALPHA_SIZE 3L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_BUFFER_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_BUFFER_SIZE 4L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_DOUBLEBUFFER
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_DOUBLEBUFFER 5L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_DEPTH_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_DEPTH_SIZE 6L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_STENCIL_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_STENCIL_SIZE 7L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_RED_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_RED_SIZE 8L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_GREEN_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_GREEN_SIZE 9L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_BLUE_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_BLUE_SIZE 10L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_ALPHA_SIZE
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCUM_ALPHA_SIZE 11L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_STEREO
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_STEREO 12L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_MULTISAMPLEBUFFERS
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_MULTISAMPLEBUFFERS 13L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_MULTISAMPLESAMPLES
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_MULTISAMPLESAMPLES 14L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCELERATED_VISUAL
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_ACCELERATED_VISUAL 15L
#undef com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_SWAP_CONTROL
#define com_badlogic_gdx_backend_sdl_Sdl_SDL_GL_SWAP_CONTROL 16L
/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    initSubSystem
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_initSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    quitSubSystem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_quitSubSystem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_quit
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    wasInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_wasInit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    getError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_getError
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    setVideoModeJni
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_setVideoModeJni
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    glSetAttribute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_glSetAttribute
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    glSwapBuffers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_glSwapBuffers
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    getBitsPerPixel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_getBitsPerPixel
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogic_gdx_backend_sdl_Sdl
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_sdl_Sdl_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_badlogic_gdx_backend_sdl_Sdl_SdlSurface */

#ifndef _Included_com_badlogic_gdx_backend_sdl_Sdl_SdlSurface
#define _Included_com_badlogic_gdx_backend_sdl_Sdl_SdlSurface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
