/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_backend_glfw_Glfw */

#ifndef _Included_com_badlogic_gdx_backend_glfw_Glfw
#define _Included_com_badlogic_gdx_backend_glfw_Glfw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_backend_glfw_Glfw
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_backend_glfw_Glfw_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
